name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build host
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j 4
    - name: build amiga
      run: |
        cmake -B build-amiga -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/amiga-vbcc.cmake
        cmake --build build-amiga -j 4

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: build host
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j 4

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: build host
      run: |
        cmake -B build
        cmake --build build --config Release
